apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tic-tac-toe-backend-certificate
  namespace: {{ namespace }}
spec:
  secretName: tic-tac-toe-backend-tls
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ hostname }}