apiVersion: apps/v1
kind: Deployment
metadata:
  name: javalin-seed-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: javalin-seed
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: javalin-seed
        branch: {{ git_branch }}
    spec:
      containers:
        - name: javalin-seed-api-container
          image: ghcr.io/ruchira088/javalin-seed-api:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: javalin-seed-data-config-map
            - secretRef:
                name: javalin-seed-secrets
          readinessProbe:
            httpGet:
              port: javalin-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              port: javalin-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-liveness-probe
          startupProbe:
            periodSeconds: 5
            failureThreshold: 5
            httpGet:
              port: javalin-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-startup-probe
          ports:
            - name: javalin-port
              containerPort: 8080
          volumeMounts:
            - mountPath: /opt/data
              name: file-config-map
      volumes:
        - name: file-config-map
          configMap:
            name: javalin-seed-file-config-map
      imagePullSecrets:
        - name: docker-registry-credentials

