apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-backend-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: tic-tac-toe-backend
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: tic-tac-toe-backend
        branch: {{ git_branch }}
    spec:
      containers:
        - name: tic-tac-toe-backend-api-container
          image: ghcr.io/ruchira088/tic-tac-toe-backend-api:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: tic-tac-toe-backend-data-config-map
            - secretRef:
                name: tic-tac-toe-backend-secrets
          readinessProbe:
            httpGet:
              port: javalin-port
              path: /service/health
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              port: javalin-port
              path: /service/health
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-liveness-probe
          startupProbe:
            periodSeconds: 5
            failureThreshold: 5
            httpGet:
              port: javalin-port
              path: /service/health
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-startup-probe
          ports:
            - name: javalin-port
              containerPort: 8080
          volumeMounts:
            - mountPath: /opt/data
              name: file-config-map
      volumes:
        - name: file-config-map
          configMap:
            name: tic-tac-toe-backend-file-config-map
      imagePullSecrets:
        - name: docker-registry-credentials

