apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: javalin-seed-ingress
  namespace: {{ namespace }}
spec:
  tls:
    - secretName: javalin-seed-tls
      hosts:
        - {{ hostname }}
  rules:
    - host: {{ hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: javalin-seed-service
                port:
                  name: javalin-port