apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-backend-service
  namespace: {{ namespace }}
spec:
  selector:
    app: tic-tac-toe-backend
    branch: {{ git_branch }}
  ports:
    - name: javalin-port
      port: 8080