services:
  tic-tac-toe-bankend:
    image: ghcr.io/ruchira088/tic-tac-toe-backend-api:main
    healthcheck:
      test: [
        "CMD",
        "curl",
        "--fail",
        "http://localhost:8080/service/health"
      ]
      interval: 10s
      timeout: 8s
      retries: 1
      start_period: 10s
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      MONGO_CONNECTION_URL: "mongodb://admin:password@mongo:27017/tic-tac-toe?authSource=admin"

  mongo:
    image: mongo:8
    healthcheck:
      test: [
        "CMD",
        "mongosh",
        "--host", "localhost",
        "--port", "27017",
        "-u", "admin",
        "-p", "password",
        "--eval", "db.adminCommand('ping')"
      ]
      interval: 10s
      timeout: 5s
      retries: 1
      start_period: 10s
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tic-tac-toe

  tic-tac-toe-front-end:
    image: ghcr.io/ruchira088/tic-tac-toe-front-end:main
#    healthcheck:
#      test: [
#        "CMD",
#        "curl",
#        "--fail",
#        "http://localhost:3000/service/health"
#      ]
#      interval: 10s
#      timeout: 8s
#      retries: 1
#      start_period: 10s
    depends_on:
      tic-tac-toe-bankend:
        condition: service_healthy
    ports:
      - "80:80"