- set_fact:
    config_values:
      MONGO_COLLECTION_NAME_SUFFIX: "{{ git_branch }}"
      MONGO_DATABASE: tic-tac-toe
    secrets:
      MONGO_CONNECTION_URL: "{{ lookup('aws_ssm', '/tic-tac-toe/database/connection-url', region='ap-southeast-2') }}"