FROM eclipse-temurin:21-jre

LABEL org.opencontainers.image.source=https://github.com/ruchira088/javalin-seed

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/javalin-seed-{{ app }}

ADD {{ app }}.tar .

CMD [ "/opt/javalin-seed-{{ app }}/{{ app }}/bin/{{ app }}" ]
