services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    healthcheck:
      test: [
        "CMD",
        "mongosh",
        "--host", "localhost",
        "--port", "27017",
        "-u", "admin",
        "-p", "password",
        "--eval", "db.adminCommand('ping')"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tic-tac-toe